# Generated by Django 3.0.2 on 2020-01-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Reporter'),
            preserve_default=False,
        ),
    ]
